version: "3.5"

services:
  db:
    image: "postgres:12-alpine"
    environment:
      - POSTGRES_USER=demo
      - POSTGRES_PASSWORD=demo-password
      - POSTGRES_DB=demo
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    volumes:
      - ".:/app"

volumes:
  postgres-data:
