FROM golang:1.13-alpine

ENV GOPATH /go
ENV PATH $GOPATH/bin:/usr/local/go/bin:$PATH

WORKDIR /go/src/app

COPY go.mod /go/src/app/go.mod
COPY go.sum /go/src/app/go.sum
RUN go mod download
RUN go get github.com/githubnemo/CompileDaemon

ENTRYPOINT CompileDaemon -log-prefix=false -build="go build -o appbin ." -command="./appbin"
